name: Build QMK firmware ZSA

on: [push, workflow_dispatch]

permissions:
    contents: write

jobs:
    build:
        name: "QMK Userspace Build"
        uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
        with:
            qmk_repo: zsa/qmk_firmware
            qmk_ref: firmware23
            preparation_command:
                "qmk userspace-remove -kb nuphy/air75_v2/ansi -km xavierchanth"

    publish:
        name: "QMK Userspace Publish"
        uses: qmk/.github/.github/workflows/qmk_userspace_publish.yml@main
        with:
            release_name: "Build-ZSA-{{github.ref}}"
        if: always() && !cancelled()
        needs: build
